name: Deploy - Beta

on:
  push:
    branches: [ "beta" ]
  workflow_dispatch:

concurrency:
  group: deploy-beta
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: beta

    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.BETA_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.BETA_HOST }} >> ~/.ssh/known_hosts

      - name: Run deploy.sh on server
        run: |
          ssh -i ~/.ssh/id_ed25519 ubuntu@${{ secrets.BETA_HOST }} "bash /home/ubuntu/7en-beta/7en-frontend/auto_deploy.sh"

      - name: Post-deploy health check
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.BETA_HOST }}
          username: ${{ secrets.BETA_USER }}
          key: ${{ secrets.BETA_SSH_KEY }}
          script: |
            set -e
            URL="https://beta.7en.ai"
            if [ -f "/var/www/beta.7en.ai/scripts/health-check.sh" ]; then
              bash /var/www/beta.7en.ai/scripts/health-check.sh beta || true
            fi
            curl -fsSL "$URL" >/dev/null && echo "Healthy" || (echo "Health check failed" && exit 1)

      - name: Notify deployment (best-effort)
        if: always()
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.BETA_HOST }}
          username: ${{ secrets.BETA_USER }}
          key: ${{ secrets.BETA_SSH_KEY }}
          script: |
            STATUS="${{ job.status }}"
            if [ -f "/var/www/beta.7en.ai/scripts/notify-deployment.sh" ]; then
              bash /var/www/beta.7en.ai/scripts/notify-deployment.sh beta "$STATUS" "GitHub Actions"
            fi
