
/**
 * Very minimal country data for demonstration.
 * Expand as needed for your use case!
 */
const countryData = [
  { code: "AF", name: "Afghanistan", dial_code: "+93", flag: "https://flagcdn.com/w20/af.png" },
  { code: "AL", name: "Albania", dial_code: "+355", flag: "https://flagcdn.com/w20/al.png" },
  { code: "DZ", name: "Algeria", dial_code: "+213", flag: "https://flagcdn.com/w20/dz.png" },
  { code: "AD", name: "Andorra", dial_code: "+376", flag: "https://flagcdn.com/w20/ad.png" },
  { code: "AO", name: "Angola", dial_code: "+244", flag: "https://flagcdn.com/w20/ao.png" },
  { code: "AG", name: "Antigua and Barbuda", dial_code: "+1268", flag: "https://flagcdn.com/w20/ag.png" },
  { code: "AR", name: "Argentina", dial_code: "+54", flag: "https://flagcdn.com/w20/ar.png" },
  { code: "AM", name: "Armenia", dial_code: "+374", flag: "https://flagcdn.com/w20/am.png" },
  { code: "AU", name: "Australia", dial_code: "+61", flag: "https://flagcdn.com/w20/au.png" },
  { code: "AT", name: "Austria", dial_code: "+43", flag: "https://flagcdn.com/w20/at.png" },
  { code: "AZ", name: "Azerbaijan", dial_code: "+994", flag: "https://flagcdn.com/w20/az.png" },
  { code: "BS", name: "Bahamas", dial_code: "+1242", flag: "https://flagcdn.com/w20/bs.png" },
  { code: "BH", name: "Bahrain", dial_code: "+973", flag: "https://flagcdn.com/w20/bh.png" },
  { code: "BD", name: "Bangladesh", dial_code: "+880", flag: "https://flagcdn.com/w20/bd.png" },
  { code: "BB", name: "Barbados", dial_code: "+1246", flag: "https://flagcdn.com/w20/bb.png" },
  { code: "BY", name: "Belarus", dial_code: "+375", flag: "https://flagcdn.com/w20/by.png" },
  { code: "BE", name: "Belgium", dial_code: "+32", flag: "https://flagcdn.com/w20/be.png" },
  { code: "BZ", name: "Belize", dial_code: "+501", flag: "https://flagcdn.com/w20/bz.png" },
  { code: "BJ", name: "Benin", dial_code: "+229", flag: "https://flagcdn.com/w20/bj.png" },
  { code: "BT", name: "Bhutan", dial_code: "+975", flag: "https://flagcdn.com/w20/bt.png" },
  { code: "BO", name: "Bolivia", dial_code: "+591", flag: "https://flagcdn.com/w20/bo.png" },
  { code: "BA", name: "Bosnia and Herzegovina", dial_code: "+387", flag: "https://flagcdn.com/w20/ba.png" },
  { code: "BW", name: "Botswana", dial_code: "+267", flag: "https://flagcdn.com/w20/bw.png" },
  { code: "BR", name: "Brazil", dial_code: "+55", flag: "https://flagcdn.com/w20/br.png" },
  { code: "BN", name: "Brunei", dial_code: "+673", flag: "https://flagcdn.com/w20/bn.png" },
  { code: "BG", name: "Bulgaria", dial_code: "+359", flag: "https://flagcdn.com/w20/bg.png" },
  { code: "BF", name: "Burkina Faso", dial_code: "+226", flag: "https://flagcdn.com/w20/bf.png" },
  { code: "BI", name: "Burundi", dial_code: "+257", flag: "https://flagcdn.com/w20/bi.png" },
  { code: "KH", name: "Cambodia", dial_code: "+855", flag: "https://flagcdn.com/w20/kh.png" },
  { code: "CM", name: "Cameroon", dial_code: "+237", flag: "https://flagcdn.com/w20/cm.png" },
  { code: "CA", name: "Canada", dial_code: "+1", flag: "https://flagcdn.com/w20/ca.png" },
  { code: "CV", name: "Cape Verde", dial_code: "+238", flag: "https://flagcdn.com/w20/cv.png" },
  { code: "CF", name: "Central African Republic", dial_code: "+236", flag: "https://flagcdn.com/w20/cf.png" },
  { code: "TD", name: "Chad", dial_code: "+235", flag: "https://flagcdn.com/w20/td.png" },
  { code: "CL", name: "Chile", dial_code: "+56", flag: "https://flagcdn.com/w20/cl.png" },
  { code: "CN", name: "China", dial_code: "+86", flag: "https://flagcdn.com/w20/cn.png" },
  { code: "CO", name: "Colombia", dial_code: "+57", flag: "https://flagcdn.com/w20/co.png" },
  { code: "KM", name: "Comoros", dial_code: "+269", flag: "https://flagcdn.com/w20/km.png" },
  { code: "CG", name: "Congo", dial_code: "+242", flag: "https://flagcdn.com/w20/cg.png" },
  { code: "CD", name: "Congo, The Democratic Republic of the", dial_code: "+243", flag: "https://flagcdn.com/w20/cd.png" },
  { code: "CR", name: "Costa Rica", dial_code: "+506", flag: "https://flagcdn.com/w20/cr.png" },
  { code: "CI", name: "Côte d'Ivoire", dial_code: "+225", flag: "https://flagcdn.com/w20/ci.png" },
  { code: "HR", name: "Croatia", dial_code: "+385", flag: "https://flagcdn.com/w20/hr.png" },
  { code: "CU", name: "Cuba", dial_code: "+53", flag: "https://flagcdn.com/w20/cu.png" },
  { code: "CY", name: "Cyprus", dial_code: "+357", flag: "https://flagcdn.com/w20/cy.png" },
  { code: "CZ", name: "Czech Republic", dial_code: "+420", flag: "https://flagcdn.com/w20/cz.png" },
  { code: "DK", name: "Denmark", dial_code: "+45", flag: "https://flagcdn.com/w20/dk.png" },
  { code: "DJ", name: "Djibouti", dial_code: "+253", flag: "https://flagcdn.com/w20/dj.png" },
  { code: "DM", name: "Dominica", dial_code: "+1767", flag: "https://flagcdn.com/w20/dm.png" },
  { code: "DO", name: "Dominican Republic", dial_code: "+1849", flag: "https://flagcdn.com/w20/do.png" },
  { code: "EC", name: "Ecuador", dial_code: "+593", flag: "https://flagcdn.com/w20/ec.png" },
  { code: "EG", name: "Egypt", dial_code: "+20", flag: "https://flagcdn.com/w20/eg.png" },
  { code: "SV", name: "El Salvador", dial_code: "+503", flag: "https://flagcdn.com/w20/sv.png" },
  { code: "GQ", name: "Equatorial Guinea", dial_code: "+240", flag: "https://flagcdn.com/w20/gq.png" },
  { code: "ER", name: "Eritrea", dial_code: "+291", flag: "https://flagcdn.com/w20/er.png" },
  { code: "EE", name: "Estonia", dial_code: "+372", flag: "https://flagcdn.com/w20/ee.png" },
  { code: "ET", name: "Ethiopia", dial_code: "+251", flag: "https://flagcdn.com/w20/et.png" },
  { code: "FJ", name: "Fiji", dial_code: "+679", flag: "https://flagcdn.com/w20/fj.png" },
  { code: "FI", name: "Finland", dial_code: "+358", flag: "https://flagcdn.com/w20/fi.png" },
  { code: "FR", name: "France", dial_code: "+33", flag: "https://flagcdn.com/w20/fr.png" },
  { code: "GA", name: "Gabon", dial_code: "+241", flag: "https://flagcdn.com/w20/ga.png" },
  { code: "GM", name: "Gambia", dial_code: "+220", flag: "https://flagcdn.com/w20/gm.png" },
  { code: "GE", name: "Georgia", dial_code: "+995", flag: "https://flagcdn.com/w20/ge.png" },
  { code: "DE", name: "Germany", dial_code: "+49", flag: "https://flagcdn.com/w20/de.png" },
  { code: "GH", name: "Ghana", dial_code: "+233", flag: "https://flagcdn.com/w20/gh.png" },
  { code: "GR", name: "Greece", dial_code: "+30", flag: "https://flagcdn.com/w20/gr.png" },
  { code: "GD", name: "Grenada", dial_code: "+1473", flag: "https://flagcdn.com/w20/gd.png" },
  { code: "GT", name: "Guatemala", dial_code: "+502", flag: "https://flagcdn.com/w20/gt.png" },
  { code: "GN", name: "Guinea", dial_code: "+224", flag: "https://flagcdn.com/w20/gn.png" },
  { code: "GW", name: "Guinea-Bissau", dial_code: "+245", flag: "https://flagcdn.com/w20/gw.png" },
  { code: "GY", name: "Guyana", dial_code: "+592", flag: "https://flagcdn.com/w20/gy.png" },
  { code: "HT", name: "Haiti", dial_code: "+509", flag: "https://flagcdn.com/w20/ht.png" },
  { code: "HN", name: "Honduras", dial_code: "+504", flag: "https://flagcdn.com/w20/hn.png" },
  { code: "HK", name: "Hong Kong", dial_code: "+852", flag: "https://flagcdn.com/w20/hk.png" },
  { code: "HU", name: "Hungary", dial_code: "+36", flag: "https://flagcdn.com/w20/hu.png" },
  { code: "IS", name: "Iceland", dial_code: "+354", flag: "https://flagcdn.com/w20/is.png" },
  { code: "IN", name: "India", dial_code: "+91", flag: "https://flagcdn.com/w20/in.png" },
  { code: "ID", name: "Indonesia", dial_code: "+62", flag: "https://flagcdn.com/w20/id.png" },
  { code: "IR", name: "Iran", dial_code: "+98", flag: "https://flagcdn.com/w20/ir.png" },
  { code: "IQ", name: "Iraq", dial_code: "+964", flag: "https://flagcdn.com/w20/iq.png" },
  { code: "IE", name: "Ireland", dial_code: "+353", flag: "https://flagcdn.com/w20/ie.png" },
  { code: "IL", name: "Israel", dial_code: "+972", flag: "https://flagcdn.com/w20/il.png" },
  { code: "IT", name: "Italy", dial_code: "+39", flag: "https://flagcdn.com/w20/it.png" },
  { code: "JM", name: "Jamaica", dial_code: "+1876", flag: "https://flagcdn.com/w20/jm.png" },
  { code: "JP", name: "Japan", dial_code: "+81", flag: "https://flagcdn.com/w20/jp.png" },
  { code: "JO", name: "Jordan", dial_code: "+962", flag: "https://flagcdn.com/w20/jo.png" },
  { code: "KZ", name: "Kazakhstan", dial_code: "+7", flag: "https://flagcdn.com/w20/kz.png" },
  { code: "KE", name: "Kenya", dial_code: "+254", flag: "https://flagcdn.com/w20/ke.png" },
  { code: "KI", name: "Kiribati", dial_code: "+686", flag: "https://flagcdn.com/w20/ki.png" },
  { code: "KP", name: "North Korea", dial_code: "+850", flag: "https://flagcdn.com/w20/kp.png" },
  { code: "KR", name: "South Korea", dial_code: "+82", flag: "https://flagcdn.com/w20/kr.png" },
  { code: "KW", name: "Kuwait", dial_code: "+965", flag: "https://flagcdn.com/w20/kw.png" },
  { code: "KG", name: "Kyrgyzstan", dial_code: "+996", flag: "https://flagcdn.com/w20/kg.png" },
  { code: "LA", name: "Laos", dial_code: "+856", flag: "https://flagcdn.com/w20/la.png" },
  { code: "LV", name: "Latvia", dial_code: "+371", flag: "https://flagcdn.com/w20/lv.png" },
  { code: "LB", name: "Lebanon", dial_code: "+961", flag: "https://flagcdn.com/w20/lb.png" },
  { code: "LS", name: "Lesotho", dial_code: "+266", flag: "https://flagcdn.com/w20/ls.png" },
  { code: "LR", name: "Liberia", dial_code: "+231", flag: "https://flagcdn.com/w20/lr.png" },
  { code: "LY", name: "Libya", dial_code: "+218", flag: "https://flagcdn.com/w20/ly.png" },
  { code: "LI", name: "Liechtenstein", dial_code: "+423", flag: "https://flagcdn.com/w20/li.png" },
  { code: "LT", name: "Lithuania", dial_code: "+370", flag: "https://flagcdn.com/w20/lt.png" },
  { code: "LU", name: "Luxembourg", dial_code: "+352", flag: "https://flagcdn.com/w20/lu.png" },
  { code: "MO", name: "Macao", dial_code: "+853", flag: "https://flagcdn.com/w20/mo.png" },
  { code: "MK", name: "North Macedonia", dial_code: "+389", flag: "https://flagcdn.com/w20/mk.png" },
  { code: "MG", name: "Madagascar", dial_code: "+261", flag: "https://flagcdn.com/w20/mg.png" },
  { code: "MW", name: "Malawi", dial_code: "+265", flag: "https://flagcdn.com/w20/mw.png" },
  { code: "MY", name: "Malaysia", dial_code: "+60", flag: "https://flagcdn.com/w20/my.png" },
  { code: "MV", name: "Maldives", dial_code: "+960", flag: "https://flagcdn.com/w20/mv.png" },
  { code: "ML", name: "Mali", dial_code: "+223", flag: "https://flagcdn.com/w20/ml.png" },
  { code: "MT", name: "Malta", dial_code: "+356", flag: "https://flagcdn.com/w20/mt.png" },
  { code: "MH", name: "Marshall Islands", dial_code: "+692", flag: "https://flagcdn.com/w20/mh.png" },
  { code: "MR", name: "Mauritania", dial_code: "+222", flag: "https://flagcdn.com/w20/mr.png" },
  { code: "MU", name: "Mauritius", dial_code: "+230", flag: "https://flagcdn.com/w20/mu.png" },
  { code: "MX", name: "Mexico", dial_code: "+52", flag: "https://flagcdn.com/w20/mx.png" },
  { code: "FM", name: "Micronesia", dial_code: "+691", flag: "https://flagcdn.com/w20/fm.png" },
  { code: "MD", name: "Moldova", dial_code: "+373", flag: "https://flagcdn.com/w20/md.png" },
  { code: "MC", name: "Monaco", dial_code: "+377", flag: "https://flagcdn.com/w20/mc.png" },
  { code: "MN", name: "Mongolia", dial_code: "+976", flag: "https://flagcdn.com/w20/mn.png" },
  { code: "ME", name: "Montenegro", dial_code: "+382", flag: "https://flagcdn.com/w20/me.png" },
  { code: "MA", name: "Morocco", dial_code: "+212", flag: "https://flagcdn.com/w20/ma.png" },
  { code: "MZ", name: "Mozambique", dial_code: "+258", flag: "https://flagcdn.com/w20/mz.png" },
  { code: "MM", name: "Myanmar", dial_code: "+95", flag: "https://flagcdn.com/w20/mm.png" },
  { code: "NA", name: "Namibia", dial_code: "+264", flag: "https://flagcdn.com/w20/na.png" },
  { code: "NR", name: "Nauru", dial_code: "+674", flag: "https://flagcdn.com/w20/nr.png" },
  { code: "NP", name: "Nepal", dial_code: "+977", flag: "https://flagcdn.com/w20/np.png" },
  { code: "NL", name: "Netherlands", dial_code: "+31", flag: "https://flagcdn.com/w20/nl.png" },
  { code: "NZ", name: "New Zealand", dial_code: "+64", flag: "https://flagcdn.com/w20/nz.png" },
  { code: "NI", name: "Nicaragua", dial_code: "+505", flag: "https://flagcdn.com/w20/ni.png" },
  { code: "NE", name: "Niger", dial_code: "+227", flag: "https://flagcdn.com/w20/ne.png" },
  { code: "NG", name: "Nigeria", dial_code: "+234", flag: "https://flagcdn.com/w20/ng.png" },
  { code: "NO", name: "Norway", dial_code: "+47", flag: "https://flagcdn.com/w20/no.png" },
  { code: "OM", name: "Oman", dial_code: "+968", flag: "https://flagcdn.com/w20/om.png" },
  { code: "PK", name: "Pakistan", dial_code: "+92", flag: "https://flagcdn.com/w20/pk.png" },
  { code: "PW", name: "Palau", dial_code: "+680", flag: "https://flagcdn.com/w20/pw.png" },
  { code: "PA", name: "Panama", dial_code: "+507", flag: "https://flagcdn.com/w20/pa.png" },
  { code: "PG", name: "Papua New Guinea", dial_code: "+675", flag: "https://flagcdn.com/w20/pg.png" },
  { code: "PY", name: "Paraguay", dial_code: "+595", flag: "https://flagcdn.com/w20/py.png" },
  { code: "PE", name: "Peru", dial_code: "+51", flag: "https://flagcdn.com/w20/pe.png" },
  { code: "PH", name: "Philippines", dial_code: "+63", flag: "https://flagcdn.com/w20/ph.png" },
  { code: "PL", name: "Poland", dial_code: "+48", flag: "https://flagcdn.com/w20/pl.png" },
  { code: "PT", name: "Portugal", dial_code: "+351", flag: "https://flagcdn.com/w20/pt.png" },
  { code: "QA", name: "Qatar", dial_code: "+974", flag: "https://flagcdn.com/w20/qa.png" },
  { code: "RO", name: "Romania", dial_code: "+40", flag: "https://flagcdn.com/w20/ro.png" },
  { code: "RU", name: "Russia", dial_code: "+7", flag: "https://flagcdn.com/w20/ru.png" },
  { code: "RW", name: "Rwanda", dial_code: "+250", flag: "https://flagcdn.com/w20/rw.png" },
  { code: "KN", name: "Saint Kitts and Nevis", dial_code: "+1869", flag: "https://flagcdn.com/w20/kn.png" },
  { code: "LC", name: "Saint Lucia", dial_code: "+1758", flag: "https://flagcdn.com/w20/lc.png" },
  { code: "VC", name: "Saint Vincent and the Grenadines", dial_code: "+1784", flag: "https://flagcdn.com/w20/vc.png" },
  { code: "WS", name: "Samoa", dial_code: "+685", flag: "https://flagcdn.com/w20/ws.png" },
  { code: "SM", name: "San Marino", dial_code: "+378", flag: "https://flagcdn.com/w20/sm.png" },
  { code: "ST", name: "Sao Tome and Principe", dial_code: "+239", flag: "https://flagcdn.com/w20/st.png" },
  { code: "SA", name: "Saudi Arabia", dial_code: "+966", flag: "https://flagcdn.com/w20/sa.png" },
  { code: "SN", name: "Senegal", dial_code: "+221", flag: "https://flagcdn.com/w20/sn.png" },
  { code: "RS", name: "Serbia", dial_code: "+381", flag: "https://flagcdn.com/w20/rs.png" },
  { code: "SC", name: "Seychelles", dial_code: "+248", flag: "https://flagcdn.com/w20/sc.png" },
  { code: "SL", name: "Sierra Leone", dial_code: "+232", flag: "https://flagcdn.com/w20/sl.png" },
  { code: "SG", name: "Singapore", dial_code: "+65", flag: "https://flagcdn.com/w20/sg.png" },
  { code: "SK", name: "Slovakia", dial_code: "+421", flag: "https://flagcdn.com/w20/sk.png" },
  { code: "SI", name: "Slovenia", dial_code: "+386", flag: "https://flagcdn.com/w20/si.png" },
  { code: "SB", name: "Solomon Islands", dial_code: "+677", flag: "https://flagcdn.com/w20/sb.png" },
  { code: "SO", name: "Somalia", dial_code: "+252", flag: "https://flagcdn.com/w20/so.png" },
  { code: "ZA", name: "South Africa", dial_code: "+27", flag: "https://flagcdn.com/w20/za.png" },
  { code: "SS", name: "South Sudan", dial_code: "+211", flag: "https://flagcdn.com/w20/ss.png" },
  { code: "ES", name: "Spain", dial_code: "+34", flag: "https://flagcdn.com/w20/es.png" },
  { code: "LK", name: "Sri Lanka", dial_code: "+94", flag: "https://flagcdn.com/w20/lk.png" },
  { code: "SD", name: "Sudan", dial_code: "+249", flag: "https://flagcdn.com/w20/sd.png" },
  { code: "SR", name: "Suriname", dial_code: "+597", flag: "https://flagcdn.com/w20/sr.png" },
  { code: "SZ", name: "Eswatini", dial_code: "+268", flag: "https://flagcdn.com/w20/sz.png" },
  { code: "SE", name: "Sweden", dial_code: "+46", flag: "https://flagcdn.com/w20/se.png" },
  { code: "CH", name: "Switzerland", dial_code: "+41", flag: "https://flagcdn.com/w20/ch.png" },
  { code: "SY", name: "Syria", dial_code: "+963", flag: "https://flagcdn.com/w20/sy.png" },
  { code: "TW", name: "Taiwan", dial_code: "+886", flag: "https://flagcdn.com/w20/tw.png" },
  { code: "TJ", name: "Tajikistan", dial_code: "+992", flag: "https://flagcdn.com/w20/tj.png" },
  { code: "TZ", name: "Tanzania", dial_code: "+255", flag: "https://flagcdn.com/w20/tz.png" },
  { code: "TH", name: "Thailand", dial_code: "+66", flag: "https://flagcdn.com/w20/th.png" },
  { code: "TL", name: "Timor-Leste", dial_code: "+670", flag: "https://flagcdn.com/w20/tl.png" },
  { code: "TG", name: "Togo", dial_code: "+228", flag: "https://flagcdn.com/w20/tg.png" },
  { code: "TO", name: "Tonga", dial_code: "+676", flag: "https://flagcdn.com/w20/to.png" },
  { code: "TT", name: "Trinidad and Tobago", dial_code: "+1868", flag: "https://flagcdn.com/w20/tt.png" },
  { code: "TN", name: "Tunisia", dial_code: "+216", flag: "https://flagcdn.com/w20/tn.png" },
  { code: "TR", name: "Turkey", dial_code: "+90", flag: "https://flagcdn.com/w20/tr.png" },
  { code: "TM", name: "Turkmenistan", dial_code: "+993", flag: "https://flagcdn.com/w20/tm.png" },
  { code: "TV", name: "Tuvalu", dial_code: "+688", flag: "https://flagcdn.com/w20/tv.png" },
  { code: "UG", name: "Uganda", dial_code: "+256", flag: "https://flagcdn.com/w20/ug.png" },
  { code: "UA", name: "Ukraine", dial_code: "+380", flag: "https://flagcdn.com/w20/ua.png" },
  { code: "AE", name: "United Arab Emirates", dial_code: "+971", flag: "https://flagcdn.com/w20/ae.png" },
  { code: "GB", name: "United Kingdom", dial_code: "+44", flag: "https://flagcdn.com/w20/gb.png" },
  { code: "US", name: "United States", dial_code: "+1", flag: "https://flagcdn.com/w20/us.png" },
  { code: "UY", name: "Uruguay", dial_code: "+598", flag: "https://flagcdn.com/w20/uy.png" },
  { code: "UZ", name: "Uzbekistan", dial_code: "+998", flag: "https://flagcdn.com/w20/uz.png" },
  { code: "VU", name: "Vanuatu", dial_code: "+678", flag: "https://flagcdn.com/w20/vu.png" },
  { code: "VA", name: "Vatican City", dial_code: "+379", flag: "https://flagcdn.com/w20/va.png" },
  { code: "VE", name: "Venezuela", dial_code: "+58", flag: "https://flagcdn.com/w20/ve.png" },
  { code: "VN", name: "Vietnam", dial_code: "+84", flag: "https://flagcdn.com/w20/vn.png" },
  { code: "YE", name: "Yemen", dial_code: "+967", flag: "https://flagcdn.com/w20/ye.png" },
  { code: "ZM", name: "Zambia", dial_code: "+260", flag: "https://flagcdn.com/w20/zm.png" },
  { code: "ZW", name: "Zimbabwe", dial_code: "+263", flag: "https://flagcdn.com/w20/zw.png" }
];

export default countryData;
